// <auto-generated />
using System;
using ComicBooks.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ComicBooks.Infrastructure.Migrations
{
    [DbContext(typeof(ComicBooksDbContext))]
    [Migration("20250416062531_AddingSections")]
    partial class AddingSections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComicBooks.Domain.Entities.FloorPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("FloorPlans");
                });

            modelBuilder.Entity("ComicBooks.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("FloorPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FloorPlanId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FloorPlanId");

                    b.HasIndex("FloorPlanId1");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("ComicBooks.Domain.Entities.Section", b =>
                {
                    b.HasOne("ComicBooks.Domain.Entities.FloorPlan", null)
                        .WithMany("Sections")
                        .HasForeignKey("FloorPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComicBooks.Domain.Entities.FloorPlan", "FloorPlan")
                        .WithMany()
                        .HasForeignKey("FloorPlanId1");

                    b.Navigation("FloorPlan");
                });

            modelBuilder.Entity("ComicBooks.Domain.Entities.FloorPlan", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
